export const defaultSexes = [
  "Female",
  "Intersex",
  "None",
  "Other",
  "Eldritch",
  "Male",
];

export const defaultPronouns = [
  ["she", "her"],
  ["they", "them"],
  ["any", "all"],
  ["he", "him"],
];

export const defaultRaces = [
  "Dwarf",
  "Orc",
  "Goblin",
  "Lizardfolk",
  "Halfling",
  "Gnome",
  "Elf",
  "Troglodyte",
  "Human",
];

export const defaultAlignments = [
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "True Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
];

export const defaultAbilities = [
  "Strength",
  "Dexterity",
  "Constitution",
  "Intellect",
  "Wisdom",
  "Charisma",
];

export const defaultQuirks = [
  "They constantly hum a tune under their breath that seems oddly familiar.",
  "Their eyes dart nervously to every shadow, even in a well-lit room, as if expecting trouble.",
  "They carry a single, wilting flower everywhere they go, gently touching its petals now and then.",
  "Despite being impeccably dressed, their boots are caked in mud that doesn't match the local terrain.",
  "They speak in riddles or metaphors, making it difficult to get a straight answer from them.",
  "A small, intricate symbol is tattooed on their wrist, partially hidden by their sleeve.",
  "They flinch visibly whenever a bell rings or a loud noise occurs.",
  "They frequently glance at the moon, even during the day, with a faraway look in their eyes.",
  "They offer you a small, polished stone as a gift, insisting it will bring you luck, then quickly try to leave.",
  "Their laughter is unnaturally loud and seems to echo long after the sound should have faded.",
  "They seem to be searching for something specific among the wares of every merchant they encounter, asking cryptic questions.",
  "They have an unusual, perhaps magical, pet that seems to communicate with them through subtle gestures.",
  "They wear a single glove on one hand, even indoors, and seem reluctant to remove it.",
  "Their voice is a hoarse whisper, as if they haven't spoken loudly in a long time.",
  "They are obsessed with collecting seemingly mundane objects, like pebbles, buttons, or dried leaves.",
  "They carry a beautiful, unstrung musical instrument, often running their fingers over the strings as if playing a silent tune.",
  "They frequently apologize for things that aren't their fault, even to inanimate objects.",
  "They have an unusual aversion to a common magical effect or creature, reacting with genuine fear or discomfort.",
  "They constantly draw in a small, worn notebook, sketching faces of people they pass, even yours.",
  "They speak with an accent that shifts subtly depending on who they're talking to, sometimes mid-sentence.",
  "They are always cold, even in warm weather, and wear layers of heavy clothing.",
  "They offer you an extremely valuable item for a pittance, but only if you promise to deliver it to a specific, hard-to-reach location.",
  "They have a distinctive scar that glows faintly when they're emotional or when magic is nearby.",
  "They talk to themselves in a language you don't understand, often having animated arguments.",
  "They are overly familiar with ancient lore or forgotten places, speaking of them as if they were there.",
  "They seem to be followed by a persistent, but unseen, draft that rustles their clothes.",
  "They insist on paying for everything with rare, antique coins that aren't in circulation.",
  "They react with intense curiosity to the most mundane objects, examining them as if they've never seen them before.",
  "They seem to have an unnatural connection to local wildlife, with birds or small animals often congregating near them.",
  "They are always looking over their shoulder, even in a seemingly safe environment, as if expecting pursuit.",
  "They wear a hat that appears to be made entirely of living mushrooms, which occasionally shift and release faint puffs of spores.",
  "They communicate solely through elaborate interpretive dance, even for simple requests like ordering a drink.",
  "Their shadow doesn't quite match their movements, lagging a step behind or occasionally doing something entirely different.",
  "They are intensely convinced they are a common farm animal (like a chicken or a pig) trapped in a humanoid body, and cluck or oink accordingly.",
  "They constantly try to sell you a 'guaranteed genuine dragon's tooth' that is clearly just a very large, oddly shaped potato.",
  "A small, sentient cloud of glitter follows them everywhere, leaving a sparkly trail and occasionally whispering secrets only they can hear.",
  "They believe all social interactions are a complex game of charades, and act out their intentions with exaggerated gestures.",
  "They collect mundane objects like spoons or buttons, but claim each one holds the soul of a powerful, ancient hero.",
  "Their laughter sounds exactly like a broken wind chime, at once musical and jarring.",
  "They insist on speaking backwards for every third word, making conversations incredibly disjointed.",
  "They have an invisible pet that they fuss over constantly, feeding it imaginary treats and scolding it for misbehavior.",
  "They try to pay for everything with 'wishes,' genuinely confused when told they aren't legal tender.",
  "They are convinced that inanimate objects are secretly plotting against them, and whisper warnings to chairs and tables.",
  "They always seem to be slightly out of sync with reality, bumping into invisible walls or walking through solid objects that are clearly there.",
  "They wear a pair of spectacles that have tiny, intricate clockwork mechanisms within the lenses, constantly whirring and ticking.",
  "They insist that all plants can talk, and spend most of their time having intense, one-sided conversations with potted ferns or garden weeds.",
  "They have a perpetually surprised expression on their face, no matter the situation, as if they've just witnessed something truly astounding.",
  "They carry a small, empty birdcage everywhere, occasionally opening the door and whispering instructions to an imaginary occupant.",
  "They only speak in rhyming couplets, often struggling to force everyday phrases into poetic form.",
  "They are convinced they are living inside a giant, invisible bubble, and occasionally mime bumping into its translucent walls.",
  "Their laughter sounds exactly like a chorus of tiny, distressed kittens.",
  "They constantly offer you 'expert advice' on the most mundane actions, like how to properly tie your shoes or open a door.",
  "They believe all coins are sentient and have distinct personalities, refusing to spend the 'grumpy' ones.",
  "They have an arm that appears to be made of pure, shimmering moonlight, which flickers when they're excited or upset.",
  "They try to trade you valuable items for utterly worthless things, like a chipped pebble or a piece of lint, genuinely believing they're getting a good deal.",
  "They wear a set of elaborate, mismatched gloves, each from a different culture or time period, and refuse to take them off.",
  "They are always slightly out of focus, as if your eyes can't quite settle on their form.",
  "They communicate primarily through a series of elaborate hand gestures and facial contortions, sometimes accompanied by strange noises.",
  "They have a pet rock they dote on more than most people care for their children, dressing it in tiny outfits and cooing at it.",
  "They frequently stop mid-sentence to listen intently to sounds only they can hear, often nodding in agreement or shaking their head in despair.",
];

export const defaultGoodTraits = [
  "Always keeps their promises.",
  "Quick to forgive.",
  "Is very generous.",
  "Acts selflessly.",
  "Shows compassion to all creatures.",
  "Speaks truthfully, even when difficult.",
  "Is fiercely loyal to their friends.",
  "Seeks justice for the wronged.",
  "Offers aid without expecting reward.",
  "Finds joy in helping others.",
  "Is optimistic, even in dire situations.",
  "Always tries to see the best in people.",
  "Is patient and understanding.",
  "Stands up for the weak.",
  "Practices temperance in all things.",
  "Values honor above personal gain.",
  "Is genuinely humble.",
  "Inspires courage in others.",
  "Is a good listener.",
  "Believes in the inherent good of life.",
];

export const defaultNeutralTraits = [
  "Values personal freedom above all else.",
  "Seeks balance in all things.",
  "Is pragmatic and realistic.",
  "Prioritizes self-preservation.",
  "Is adaptable and flexible.",
  "Avoids taking extreme stances.",
  "Is often impartial.",
  "Follows their own moral code.",
  "Is fiercely independent.",
  "Trusts their instincts.",
  "Is resourceful.",
  "Prefers quiet observation to direct action.",
  "Acts out of self-interest, but not maliciously.",
  "Is cautious and considers all outcomes.",
  "Respects the natural order of things.",
  "Is skeptical of grand ideologies.",
  "Finds comfort in routine.",
  "Is resilient in the face of change.",
  "Keeps their own counsel.",
  "Is opportunistic.",
];
export const defaultLawfulTraits = [
  "Adheres strictly to rules and laws.",
  "Values tradition and established order.",
  "Is highly disciplined.",
  "Always honors their word.",
  "Believes in clear hierarchies.",
  "Is meticulously organized.",
  "Respects authority.",
  "Prioritizes duty above personal desires.",
  "Is reliable and dependable.",
  "Upholds justice and fairness through law.",
  "Is resistant to chaos and anarchy.",
  "Demands accountability.",
  "Is patient and methodical.",
  "Follows established procedures.",
  "Seeks to improve society through structure.",
  "Is honorable in all dealings.",
  "Expects others to follow rules.",
  "Is a pillar of the community.",
  "Avoids impulsive actions.",
  "Sacrifices personal freedom for the greater good.",
];

export const defaultChaoticTraits = [
  "Values individual freedom above all laws.",
  "Acts impulsively.",
  "Is unpredictable.",
  "Challenges authority.",
  "Dislikes rigid rules and structures.",
  "Is adaptable and opportunistic.",
  "Follows their own whims.",
  "Is spontaneous.",
  "Rebels against established norms.",
  "Trusts their gut feelings.",
  "Is often mischievous.",
  "Prioritizes personal desires.",
  "Is fiercely independent.",
  "Seeks excitement and change.",
  "Disregards tradition.",
  "Is resourceful in unconventional ways.",
  "Can be unreliable.",
  "Embraces disorder.",
  "Is not bound by promises or contracts.",
  "Prefers anarchy over tyranny.",
];

export const defaultEvilTraits = [
  "Is completely self-serving.",
  "Manipulates others for personal gain.",
  "Shows no remorse for their actions.",
  "Enjoys inflicting pain or suffering.",
  "Is power-hungry.",
  "Is deceitful and untrustworthy.",
  "Lacks empathy.",
  "Seeks to dominate or control.",
  "Is cruel and sadistic.",
  "Exploits weaknesses in others.",
  "Is arrogant and contemptuous.",
  "Betrays allies without hesitation.",
  "Is vengeful and holds grudges.",
  "Finds pleasure in destruction.",
  "Is exceptionally greedy.",
  "Prizes their own life above all others'.",
  "Is cunning and calculating.",
  "Disregards moral boundaries.",
  "Is hateful and prejudiced.",
  "Corrupts anything they touch.",
];

export type NPC = {
  name: string;
  sex: string;
  pronouns: [string, string];
  race: string;
  abilities: { [key: string]: number }[];
  alignment: string;
  quirk: string;
  personality: string[];
};
